maps:
  battlefield:
    deathY: 40
    spawns:
      - x: 100
        y: 80
        z: 100
        yaw: 90
        pitch: 0
      - x: 110
        y: 80
        z: 100
        yaw: 270
        pitch: 0
