maps:
  your_map_name_here:
    deathY: 0
    spawns:
      - x: 538
        y: 46
        z: 678
        yaw: 0
        pitch: 0
  map_with_multiple_spawns:
    deathY: 10
    spawns:
      - x: 37
        y: 46
        z: 387
        yaw: -180
        pitch: 0
      - x: 37
        y: 46
        z: 372
        yaw: 0
        pitch: 0